[package]
name = "grits"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["cargo", "derive"] }
clap_complete = "4.5.38"
crossterm = "0.28.1"
env_logger = "0.11.5"
indoc = "2.0.5"
log = "0.4.22"
regex = "1.11.1"
